=== joseespejo17/Ejercicios_LMSGI/Examenes/Examen01.dtd
<!ELEMENT videoClub (peliculas, ofertas)>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT ofertas (oferta*)>
<!ELEMENT pelicula (nombre, duracion?, precio, (existencias | agotado))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT duracion EMPTY>
<!ELEMENT precio EMPTY>
<!ELEMENT existencias EMPTY>
<!ELEMENT agotado EMPTY>
<!ELEMENT oferta (#PCDATA | peliculasReferidas)*>
<!ELEMENT peliculasReferidas ANY>
<!ATTLIST videoClub direccion CDATA #IMPLIED 
                      nombre CDATA #REQUIRED
                      telefono CDATA #FIXED "957591456">
<!ATTLIST pelicula codigo ID #REQUIRED
                temaPrincipal (Terror | CienciaFiccion | Fantasia) "Terror">
<!ATTLIST peliculasReferidas codigopelicula IDREF #REQUIRED
                         otroCodigosPeliculas IDREFS #IMPLIED>
<!ENTITY % atributoCoste "coste CDATA #IMPLIED"> 
<!ATTLIST precio %atributoCoste;>
<!ATTLIST oferta %atributoCoste;>
<!ENTITY dura "2h y 28m">

=== joseespejo17/Ejercicios_LMSGI/Examenes/Examen01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoClub SYSTEM "Examen01.dtd">
<videoClub direccion="Calle Rute" nombre="DiViDendo" telefono="957591456">
  <peliculas>
    <pelicula codigo="terr" temaPrincipal ="Terror">
      <nombre>Insiduous</nombre>
      <duracion/>
      <precio coste="3'5" />
      <existencias />
    </pelicula>
    <pelicula codigo="cien">
      <nombre>Spider-man &dura;</nombre>
      <precio coste="5" />
      <agotado />
    </pelicula>
  </peliculas>
  <ofertas>
      <oferta coste="10">3x1 
        <peliculasReferidas codigopelicula="terr" otroCodigosPeliculas="cien " />
       
      </oferta>
  </ofertas>
</videoClub>
